##Start by reading file, adjusting variables and subsetting data, the same for all scripts
hpw<-read.table("household_power_consumption.txt", header= TRUE, sep=";") 
hpw$Date<-as.Date(as.character(hpw$Date), "%d/%m/%Y")
hpw<-subset(hpw, Date == "2007/02/01" | Date == "2007/02/02")
hpw$Time<-as.POSIXct(paste(as.character(hpw$Date),as.character(hpw$Time)))
hpw$Sub_metering_1<-as.numeric(as.character(hpw$Sub_metering_1))
hpw$Sub_metering_2<-as.numeric(as.character(hpw$Sub_metering_2))
hpw$Sub_metering_3<-as.numeric(as.character(hpw$Sub_metering_3))
hpw$Global_active_power<-as.numeric(as.character(hpw$Global_active_power))
hpw$Global_reactive_power<-as.numeric(as.character(hpw$Global_reactive_power))
hpw$Voltage<-as.numeric(as.character(hpw$Voltage))
##Prepare device, plot and add whatever is asked on each case. Finally close device
png(filename="plot4.png", width=480, height=480) 
par(mfrow=c(2,2))
plot(hpw$Time, hpw$Global_active_power, type="l", ylab = "Global Active Power", xlab="", yaxt="n")
axis(2, ylim=c(0,8), at=c(0,2,4,6), labels=c("0","2","4","6"))
plot(hpw$Time, hpw$Voltage, type="l", ylab = "Voltage", xlab="datetime", yaxt="n")
axis(2, ylim=c(230,250,8), at=c(234,236,238,240,242,244,246), labels=c("234","","238","","242","","246"))
plot(hpw$Time, hpw$Sub_metering_1, type="l", ylab = "Energy Sub Metering", xlab="", yaxt="n")
axis(2, at=c(0,10,20,30), labels=c("0","10","20","30"))
lines(hpw$Time, hpw$Sub_metering_2, col = "red")
lines(hpw$Time, hpw$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=3, col=c("black", "red", "blue"), bty="n")
plot(hpw$Time, hpw$Global_reactive_power, type="l", ylab = "Global_reactive_power", xlab="datetime", yaxt="n")
axis(2, at=c(0.0,0.1,0.2,0.3,0.4,0.5), labels=c("0.0","0.1","0.2","0.3","0.4","0.5"))
dev.off()